# Compiled automatically from CarrierSettings.pb overlays via Gemini

[[carrier_id]]
mcc_mnc = "23457"
gid1 = "0C"

[[carrier_id]]
mcc_mnc = "23457"
imsi_prefix_xpattern = "234570000"

[[carrier_id]]
mcc_mnc = "23457"
spn = "Sky"

[[carrier_id]]
mcc_mnc = "23457"

[[carrier_id]]
mcc_mnc = "24007"
gid1 = "0C"

[[carrier_id]]
mcc_mnc = "24007"
spn = "Sky"

[settings]
version = 75000000018

[[settings.apns.apn]]
authtype = 0
bearer_bitmask = "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|17|20"
mmsc = "http://185.110.178.96:38090/was"
mmsc_proxy = "185.110.178.97"
mmsc_proxy_port = "9028"
name = "SKY MMS"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "mms" ]
user_visible = false
value = "mms.mobile.sky"

[[settings.apns.apn]]
authtype = 0
bearer_bitmask = "18"
mmsc = "http://185.110.178.96:38090/was"
mmsc_proxy = "185.110.178.97"
mmsc_proxy_port = "9028"
name = "SKY WiFi MMS"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "mms" ]
user_visible = false
value = "wifi.mms.mobile.sky"

[[settings.apns.apn]]
name = "SKY Internet"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "default", "supl", "ia" ]
value = "mobile.sky"

[[settings.apns.apn]]
bearer_bitmask = "14|18|20"
name = "IMS"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "ims" ]
user_visible = false
value = "ims"

[[settings.apns.apn]]
bearer_bitmask = "14|18|20"
name = "Sky Ut"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "xcap" ]
user_visible = false
value = "ut.mobile.sky"

[settings.config]
call_barring_visibility = true
carrier_default_wfc_ims_enabled = true
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
editable_wfc_mode = false
maxMessageSize = 307200
non_roaming_operator = [
    "23410",
    "23426",
    "23430",
    "23431",
    "23432",
    "23433",
    "23434",
    "23486"
]
prefer_2g = false
show_4g_for_lte_data_icon = true
sim_country_iso_override = "gb"
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.ims.mnc057.mcc234.pub.3gppnetwork.org"

[settings.config.ims]
ipv4_sip_mtu_size_cellular = 1280
ipv6_sip_mtu_size_cellular = 1280
sip_timer_b_millis = 90000
sip_timer_f_millis = 32000
sip_timer_j_millis = 32000

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_as_server_fqdn = "xcap.ims.mnc057.mcc234.pub.3gppnetwork.org"
ut_requires_ims_registration = true
ut_server_based_services = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    15,
    19,
    8,
    11,
    9
]
xcap_over_ut_supported_rats = [ 5, 6, 3 ]

[settings.config.imsvoice]
audio_codec_capability_payload_types = { imsvoice = { amrnb_payload_type = [ 102 ], amrwb_payload_type = [ 104 ], dtmfnb_payload_type = [ 97 ], dtmfwb_payload_type = [ 96 ], evs_payload_type = [ 127 ] } }
conference_subscribe_type = 0
dedicated_bearer_wait_timer_millis = 10000
evs_payload_description = { 127 = { imsvoice = { codec_attribute_cmr = 2, evs_codec_attribute_bitrate = [ 0, 6 ], evs_codec_attribute_ch_aw_recv = 255, evs_codec_attribute_hf_only = 0 } } }
minimum_session_expires_timer_sec = 600
oip_source_from_header = true
prack_supported_for_18x = true

[settings.config.vendor]
ims = { carrier_config_use_aosp_ims_config = true }
