# Compiled automatically from CarrierSettings.pb overlays via Gemini

[[carrier_id]]
mcc_mnc = "23405"
spn = "Spitfire"

[settings]
version = 77000000002

[settings.config.imsvoice]
amrnb_payload_description = { 103 = { imsvoice = { amr_codec_attribute_modeset = [
    0,
    2,
    4,
    7
], amr_codec_attribute_payload_format = 1 } }, 98 = { imsvoice = { amr_codec_attribute_modeset = [
    0,
    2,
    4,
    7
] } } }
audio_codec_capability_payload_types = { imsvoice = { amrnb_payload_type = [ 98, 103 ], amrwb_payload_type = [ 100, 105 ], dtmfnb_payload_type = [ 97 ], dtmfwb_payload_type = [ 96 ] } }
prack_supported_for_18x = true
