# Compiled automatically from CarrierSettings.pb overlays via Gemini

[[carrier_id]]
mcc_mnc = "20601"
gid1 = "28000000"

[[carrier_id]]
mcc_mnc = "20620"
gid1 = "28000000"

[[carrier_id]]
mcc_mnc = "23430"
gid1 = "28000000"

[[carrier_id]]
mcc_mnc = "23438"

[settings]
version = 77000000004

[[settings.apns.apn]]
authtype = 1
mmsc = "http://mms.virginmobile.co.uk:8002"
mmsc_proxy = "193.30.166.2"
mmsc_proxy_port = "8080"
name = "Virgin Media Mobile Internet"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
type = [ "default", "mms", "supl" ]
user = "user"
value = "goto.virginmobile.uk"

[[settings.apns.apn]]
bearer_bitmask = "14"
name = "XCAP"
protocol = "ipv4v6"
type = [ "xcap" ]
user_visible = false
value = "hos"

[[settings.apns.apn]]
bearer_bitmask = "14|18|20"
mtu = 1280
name = "ims"
protocol = "ipv4v6"
type = [ "ims" ]
user_visible = false
value = "IMS"

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 2
carrier_name = "Virgin"
carrier_name_override = true
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
carrier_wfc_ims_available = true
editable_wfc_mode = false
hide_ims_apn = true
non_roaming_operator = [
    "23430",
    "23431",
    "23432",
    "23433",
    "23434",
    "23486"
]
prefer_2g = true
show_4g_for_lte_data_icon = true
sim_country_iso_override = "gb"
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_port = 8080

[settings.config.ims]
geolocation_pidf_in_sip_invite_support = [ 4, 2 ]
geolocation_pidf_in_sip_register_support = [ 4, 2 ]
ims_user_agent = "#MANUFACTURE# #MODEL# #BUILD#"
ipsec_authentication_algorithms = [ 1 ]
ipsec_encryption_algorithms = [ 2 ]
ipv4_sip_mtu_size_cellular = 1280
ipv6_sip_mtu_size_cellular = 1280
request_uri_type = 1

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_iptype_home = 0
ut_iptype_roaming = 0
ut_requires_ims_registration = true
xcap_over_ut_supported_rats = [ 3 ]

[settings.config.imsvoice]
evs_payload_description = { 127 = { imsvoice = { evs_codec_attribute_bitrate = [ 0, 6 ], evs_codec_attribute_ch_aw_recv = -1 } } }
ringback_timer_millis = 180000
ringing_timer_millis = 180000
session_privacy_type = 2

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 86500
child_sa_rekey_soft_timer_sec = 86400
diffie_hellman_groups = [ 14 ]
epdg_static_address = "epdg.epc.mnc038.mcc234.pub.3gppnetwork.org"
ike_rekey_hard_timer_in_sec = 86500
ike_rekey_soft_timer_sec = 86400
ike_remote_id_type = 11
key_error_policy_config = "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9000\"],\"RetryArray\": [],\"UnthrottlingEvents\": [\"WIFI_DISABLE_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"10500\"],\"RetryArray\": [\"30\", \"30\", \"30\", \"30\", \"30\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"

[settings.config.qns]
xcap_transport_type = 0
