# Compiled automatically from CarrierSettings.pb overlays via Gemini

[[carrier_id]]
mcc_mnc = "23430"
spn = "LycaMobile"

[settings]
version = 77000000001

[settings.config]
carrier_volte_available = true
non_roaming_operator = [
    "23410",
    "23420",
    "23430",
    "23431",
    "23432",
    "23433",
    "23434",
    "23486"
]
show_4g_for_lte_data_icon = true
