[[carrier_id]]
mcc_mnc = "23418"
[carrier_id.mvno_data]
kind  = "gid1"
value = "6764"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "globaldata"
value = "globaldata"
type = ["default", "supl", "dun"]

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
bearer_bitmask = "14|20"
user_visible = false

[settings.config]
imsvoice.amrnb_payload_description_bundle = { 103 = { imsvoice.amr_codec_attribute_modeset = [0, 2, 4, 7], imsvoice.amr_codec_attribute_payload_format = 1 }, 98 = { imsvoice.amr_codec_attribute_modeset = [0, 2, 4, 7] } }
imsvoice.audio_codec_capability_payload_types_bundle = { imsvoice.amrnb_payload_type = [98, 103], imsvoice.amrwb_payload_type = [100, 105], imsvoice.dtmfnb_payload_type = [97], imsvoice.dtmfwb_payload_type = [96] }
imsvoice.oip_source_from_header = true
imsvoice.prack_supported_for_18x = true
read_only_apn_types_string_array = { kind = "text_array", value = [] }
