[[carrier_id]]
mcc_mnc = "23415"

[[carrier_id]]
mcc_mnc = "23491"

[settings]
version = 77000000013

[[settings.apns.apn]]
name = "Vodafone UK Data"
value = "wap.vodafone.co.uk"
type = ["default", "mms", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
authtype = 1
mmsc = "http://mms.vodafone.co.uk/servlets/mms"
mmsc_proxy = "212.183.137.12"
mmsc_proxy_port = "8799"
mtu = 1340
password = "wap"
user = "wap"
user_editable = false

[[settings.apns.apn]]
name = "IMS"
value = "IMS"
type = ["ims"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
bearer_bitmask = "14|18|20"
user_visible = false

[[settings.apns.apn]]
name = "XCAP"
value = "xcap"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
call_barring_visibility = true
carrier_certificate_string_array = { kind = "text_array", value = ["2E26357C65C1F858CE0C798AA7EFB38922E8D334F12DAD4A3963007DFBBC5677:com.myvodafoneapp"] }
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_mode = 1
carrier_nr_availabilities = [1, 2]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "121"
epsfb_silent_retry_error_code_string_array = { kind = "text_array", value = ["500", "503"] }
feature_access_codes_string_array = { kind = "text_array", value = ["153", "132", "45"] }
hide_enhanced_4g_lte = true
ims_reasoninfo_mapping_string_array = { kind = "text_array", value = ["338|busy everywhere|1017", "510|Call completed elsewhere|1014"] }
imsss.network_initiated_ussd_over_ims_supported = false
imsss.xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]
imsvoice.audio_codec_capability_payload_types_bundle = { imsvoice.amrnb_payload_type = [102], imsvoice.amrwb_payload_type = [104], imsvoice.dtmfnb_payload_type = [97], imsvoice.dtmfwb_payload_type = [96], imsvoice.evs_payload_type = [127] }
imsvoice.conference_subscribe_type = 0
imsvoice.evs_payload_description_bundle = { 127 = { imsvoice.evs_codec_attribute_bitrate = [0, 6] } }
imsvoice.minimum_session_expires_timer_sec = 600
imsvoice.ringback_timer_millis = 180000
imsvoice.ringing_timer_millis = 180000
imsvoice.session_refresh_method = 0
imsvoice.session_refresher_type = 0
min_udp_port_4500_nat_timeout_sec = 120
qns.block_iwlan_in_international_roaming_without_wwan = true
qns.idle_eutran_rsrp = [18446744073709551506, 18446744073709551500]
qns.idle_geran_rssi = [18446744073709551562, 18446744073709551556]
qns.idle_utran_rscp = [18446744073709551511, 18446744073709551506]
qns.ims_wlan_hysteresis_timer_ms = [5000, 5000, 5000]
qns.ims_wwan_hysteresis_timer_ms = [5000, 5000, 5000]
qns.support_wfc_recovery = false
qns.video_eutran_rsrp = [18446744073709551506, 18446744073709551500]
qns.video_geran_rssi = [18446744073709551517, 18446744073709551514]
qns.video_utran_rscp = [18446744073709551511, 18446744073709551506]
qns.voice_eutran_rsrp = [18446744073709551506, 18446744073709551500]
qns.voice_geran_rssi = [18446744073709551517, 18446744073709551514]
qns.voice_utran_rscp = [18446744073709551511, 18446744073709551506]
read_only_apn_types_string_array = { kind = "text_array", value = [] }
show_4g_for_lte_data_icon = true
smsToMmsTextThreshold = { kind = "int", value = 10 }
voicemail_notification_persistent = true
volte_vowifi_silent_retry_error_code_string_array = { kind = "text_array", value = ["500", "503"] }
vonr_enabled = true
vonr_setting_visibility = false
wfc_spn_format_idx = 12

[settings.config.ims]
ipv4_sip_mtu_size_cellular = 1280
ipv6_sip_mtu_size_cellular = 1280
registration_event_package_supported = false

[settings.config.iwlan]
diffie_hellman_groups = [2]
ike_remote_id_type = 11
key_error_policy_config = "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9002\"],\"RetryArray\": [\"1800\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
mcc_mncs_string_array = { kind = "text_array", value = ["235-015"] }
natt_keep_alive_timer_sec = 30
